name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun i --frozen-lockfile

      - name: Run checks
        run: bun --bun run lint

      - name: Build
        run: bun --bun run build
